# Generated by Django 4.0.1 on 2022-01-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technobaza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
