# Generated by Django 4.0 on 2021-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='phones/images'),
        ),
    ]
