# Generated by Django 4.0 on 2021-12-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDLib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='cover',
            field=models.ImageField(default='test.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
