# Generated by Django 4.0 on 2021-12-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'managed': True},
        ),
    ]
