# Generated by Django 4.0 on 2021-12-18 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0002_alter_manufacturer_options_alter_phone_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='manufacturer',
            field=models.ForeignKey(db_column='manufacturer', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lab_api.manufacturer'),
            preserve_default=False,
        ),
    ]
