# Generated by Django 4.0 on 2021-12-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0003_phone_description_phone_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
