# Generated by Django 4.0 on 2021-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_api', '0004_phone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
